import {
  requestAuthenticateOptions,
  requestAuthenticateVerify,
  requestRegisterOptions,
  requestRegisterVerify,
  requestRemoveCredentials,
  webauthnController,
} from "./controller"
import { endpoint } from "./endpoints"
import type {
  WebAuthnAssertionResponseDto,
  WebAuthnAttestationResponseDto,
  WebAuthnAuthenticateCredentialRequestDto,
  WebAuthnAuthenticateOptionsRequestDto,
  WebAuthnAuthenticateOptionsResponseDto,
  WebAuthnAuthenticatorSelection,
  WebAuthnBase64Url,
  WebAuthnCredentialDescriptor,
  WebAuthnPubKeyCredParam,
  WebAuthnRegisterCredentialRequestDto,
  WebAuthnRegisterOptionsResponseDto,
  WebAuthnRegisterResultResponseDto,
  WebAuthnRpEntity,
  WebAuthnSessionResponseDto,
  WebAuthnTransport,
  WebAuthnUserEntity,
} from "./dto"

export {
  endpoint,
  requestAuthenticateOptions,
  requestAuthenticateVerify,
  requestRegisterOptions,
  requestRegisterVerify,
  requestRemoveCredentials,
  webauthnController,
}
export type {
  WebAuthnAssertionResponseDto,
  WebAuthnAttestationResponseDto,
  WebAuthnAuthenticateCredentialRequestDto,
  WebAuthnAuthenticateOptionsRequestDto,
  WebAuthnAuthenticateOptionsResponseDto,
  WebAuthnAuthenticatorSelection,
  WebAuthnBase64Url,
  WebAuthnCredentialDescriptor,
  WebAuthnPubKeyCredParam,
  WebAuthnRegisterCredentialRequestDto,
  WebAuthnRegisterOptionsResponseDto,
  WebAuthnRegisterResultResponseDto,
  WebAuthnRpEntity,
  WebAuthnSessionResponseDto,
  WebAuthnTransport,
  WebAuthnUserEntity,
}
