/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appChartRouteImport } from './routes/(app)/chart'
import { Route as appHomeRouteImport } from './routes/(app)/home'
import { Route as appOptionsRouteImport } from './routes/(app)/options'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appTradeRouteImport } from './routes/(app)/trade'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authPinRouteImport } from './routes/(auth)/pin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appChartRoute = appChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => appRouteRoute,
} as any)
const appHomeRoute = appHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => appRouteRoute,
} as any)
const appOptionsRoute = appOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => appRouteRoute,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appTradeRoute = appTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authPinRoute = authPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chart': typeof appChartRoute
  '/home': typeof appHomeRoute
  '/options': typeof appOptionsRoute
  '/profile': typeof appProfileRoute
  '/trade': typeof appTradeRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/pin': typeof authPinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chart': typeof appChartRoute
  '/home': typeof appHomeRoute
  '/options': typeof appOptionsRoute
  '/profile': typeof appProfileRoute
  '/trade': typeof appTradeRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/pin': typeof authPinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/chart': typeof appChartRoute
  '/(app)/home': typeof appHomeRoute
  '/(app)/options': typeof appOptionsRoute
  '/(app)/profile': typeof appProfileRoute
  '/(app)/trade': typeof appTradeRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/pin': typeof authPinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chart'
    | '/home'
    | '/options'
    | '/profile'
    | '/trade'
    | '/login'
    | '/otp'
    | '/pin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chart'
    | '/home'
    | '/options'
    | '/profile'
    | '/trade'
    | '/login'
    | '/otp'
    | '/pin'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/(app)/chart'
    | '/(app)/home'
    | '/(app)/options'
    | '/(app)/profile'
    | '/(app)/trade'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/(auth)/pin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/chart': {
      id: '/(app)/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof appChartRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/home': {
      id: '/(app)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof appHomeRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/options': {
      id: '/(app)/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof appOptionsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/trade': {
      id: '/(app)/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof appTradeRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/pin': {
      id: '/(auth)/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof authPinRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appChartRoute: typeof appChartRoute
  appHomeRoute: typeof appHomeRoute
  appOptionsRoute: typeof appOptionsRoute
  appProfileRoute: typeof appProfileRoute
  appTradeRoute: typeof appTradeRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appChartRoute: appChartRoute,
  appHomeRoute: appHomeRoute,
  appOptionsRoute: appOptionsRoute,
  appProfileRoute: appProfileRoute,
  appTradeRoute: appTradeRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  authPinRoute: typeof authPinRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  authPinRoute: authPinRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
