import type {
  WebAuthnAssertionResponseDto,
  WebAuthnAttestationResponseDto,
  WebAuthnAuthenticateCredentialRequestDto,
  WebAuthnAuthenticateOptionsRequestDto,
  WebAuthnAuthenticateOptionsResponseDto,
  WebAuthnAuthenticatorSelection,
  WebAuthnBase64Url,
  WebAuthnCredentialDescriptor,
  WebAuthnPubKeyCredParam,
  WebAuthnRegisterCredentialRequestDto,
  WebAuthnRegisterOptionsResponseDto,
  WebAuthnRegisterResultResponseDto,
  WebAuthnRpEntity,
  WebAuthnSessionResponseDto,
  WebAuthnTransport,
  WebAuthnUserEntity,
} from "./webauthn.dto"

export type {
  WebAuthnAssertionResponseDto,
  WebAuthnAttestationResponseDto,
  WebAuthnAuthenticateCredentialRequestDto,
  WebAuthnAuthenticateOptionsRequestDto,
  WebAuthnAuthenticateOptionsResponseDto,
  WebAuthnAuthenticatorSelection,
  WebAuthnBase64Url,
  WebAuthnCredentialDescriptor,
  WebAuthnPubKeyCredParam,
  WebAuthnRegisterCredentialRequestDto,
  WebAuthnRegisterOptionsResponseDto,
  WebAuthnRegisterResultResponseDto,
  WebAuthnRpEntity,
  WebAuthnSessionResponseDto,
  WebAuthnTransport,
  WebAuthnUserEntity,
}
