import type {
  WebAuthnAssertionResponseDto,
  WebAuthnAttestationResponseDto,
  WebAuthnAuthenticateCredentialDto,
  WebAuthnAuthenticateOptionsDto,
  WebAuthnAuthenticateOptionsRequestDto,
  WebAuthnAuthenticatorSelection,
  WebAuthnBase64Url,
  WebAuthnCredentialDescriptor,
  WebAuthnPubKeyCredParam,
  WebAuthnRegisterCredentialDto,
  WebAuthnRegisterOptionsDto,
  WebAuthnRegisterResultDto,
  WebAuthnRpEntity,
  WebAuthnSessionDto,
  WebAuthnTransport,
  WebAuthnUserEntity,
} from './webauthn.dto'

export type {
  WebAuthnAssertionResponseDto,
  WebAuthnAttestationResponseDto,
  WebAuthnAuthenticateCredentialDto,
  WebAuthnAuthenticateOptionsDto,
  WebAuthnAuthenticateOptionsRequestDto,
  WebAuthnAuthenticatorSelection,
  WebAuthnBase64Url,
  WebAuthnCredentialDescriptor,
  WebAuthnPubKeyCredParam,
  WebAuthnRegisterCredentialDto,
  WebAuthnRegisterOptionsDto,
  WebAuthnRegisterResultDto,
  WebAuthnRpEntity,
  WebAuthnSessionDto,
  WebAuthnTransport,
  WebAuthnUserEntity,
}
